feat(auth): add register & login

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,33 +1,37 @@
 #!/bin/sh
 . "$(dirname "$0")/_/husky.sh"
 
-echo ' Styling, testing and building your project before committing'
+echo "🧹 Styling, testing and building your project before committing..."
 
 # Check Prettier
 npm run check-format ||
 (
-    echo 'Prettier Check Failed. Run npm run format, add changes and try commit again';
+    echo "❌ Prettier Check Failed. Run: npm run format, add changes, and try commit again"
     false;
 )
 
 # Check ESLint
 npm run check-lint ||
 (
-    echo "ESLint Check Failed. Make the required changes listed above, add changes and try to commit again";
+    echo "❌ ESLint Check Failed. Fix the issues listed above, add changes, and try commit again"
     false;
 )
 
 # Check tsconfig
-npm run check-types || 
+npm run check-types ||
 (
-    echo "Failed type check. Make the changes require above, add changes and try to commit again";
+    echo "❌ Type check failed. Fix the issues listed above, add changes, and try commit again"
     false;
 )
 
+# Build
 npm run build ||
 (
-    echo "Your build failed, view the errors above"
+    echo "❌ Build failed. See errors above"
     false;
 )
 
-echo "Success Commit"
+echo "✅ Success! Ready to commit 🚀"
+
+echo "🔄 Auto staging changes before commit..."
+git add .
